finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='finches_index'),
    path('finches/<int:finch_id>/', views.finches_detail, name='finches_detail'),
    path('finches/create/', views.FinchesCreate.as_view(), name='finches_create'),
    path('finches/<int:pk>/update/', views.FinchesUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete', views.FinchesDelete.as_view(), name='finches_delete'),
    path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)

# Create your models here.
class Finch(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('finches_detail', kwargs={'finch_id': self.id })    

class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1, 
        choices=MEALS, 
        default=MEALS[0][0]
    )
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE) 

    def __str__(self):
        return f'{self.get_meal_display()} on {self.date}'

class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ('date', 'meal')

main_app/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms  import FeedingForm
from django.contrib.auth.forms import UserCreationForm

from .models import Finch

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def finches_index(request):
    finches = Finch.objects.filter(user=request.user)
    return render(request, 'finches/index.html', {'finches': finches})

@login_required
def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    feeding_form = FeedingForm()
    return render(request, 'finches/detail.html', {
        'finch': finch, 
        'feeding_form': feeding_form
    })

@login_required
def add_feeding(request, finch_id):
    form = FeedingForm(request.POST) 
    
    if form.is_valid():
      new_feeding = form.save(commit=False) 
      new_feeding.finch_id = finch_id
      new_feeding.save()
    else: 
        print(form.errors)
    return redirect('finches_detail', finch_id=finch_id)


def signup(request):
    # POST Request
    error_message = None
    if request.method == 'POST':
        # Capture user input from a form
        form = UserCreationForm(request.POST)
        # checl the form to ensure it's a valiD
        if form.is_valid():
            # use the user input to create a new user in the database
            user = form.save()
            # log the user in
            login(request, user)
            # redirect the user to the cats_index page
            return redirect('finches_index')
        else:
            error_message = 'Signup input invalid - Please try again'
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form })

class FinchesCreate(LoginRequiredMixin, CreateView):
    model = Finch
    fields = ('name', 'breed', 'description', 'age')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class FinchesUpdate(LoginRequiredMixin, UpdateView):
    model = Finch
    fields = ('age', 'description')

class FinchesDelete(LoginRequiredMixin, DeleteView):
    model = Finch
    success_url = '/finches/'

main_app/templates/about.html
{% extends 'base.html' %}

{% block title %}
About | Finch Collector
{% endblock %}

{% block content %}
<h1>About</h1>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="left brand-logo">  Finch Collector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'finches_index' %}">View all my Finches</a></li>
            <li><a href="{% url 'finches_create' %}">Add a New Finches</a></li>
            <li><a href="{% url 'logout' %}">Logout</li></a>
            {% else %}
            <li><a href="{% url 'login' %}">Login</li></a>
            <li><a href="{% url 'signup' %}">Signup</li></a>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">
        {% block content %} 
        {% endblock %}
    </main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, © 2019 Finch Collector  
      </div>
    </footer>
  </body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Finch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Breed: {{ finch.breed }}</p>
        <p>Description: {{ finch.description }}</p>
        {% if finch.age > 0 %}
        <p>Age: {{ finch.age }}</p>
        {% else %}
        <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'finches_update' finch.id %}">Update</a>
        <a href="{% url 'finches_delete' finch.id %}">Delete</a>
      </div>
  </div>
</div>
  <div class="col s6">

    <form action="{% url 'add_feeding' finch.id %}" method="POST">
        {% csrf_token %}
        
        {{ feeding_form.as_p }}
        <input class="btn blue" type="submit" value="Add Feeding">
    </form>

    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
          <tr>
            <td>{{ feeding.date }}</td>
            <td>{{ feeding.get_meal_display }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script>
  const dateField = document.getElementById('id_date');
  const mealSelect = document.getElementById('id_meal');

  M.Datepicker.init(dateField, {
      format: 'mmm dd, yyyy',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
  });

  M.FormSelect.init(mealSelect);
</script>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}

{% block title %}
Finches Index | Finches Collector
{% endblock %}

{% block content %}
<h1>Finches Index</h1>

{% for finch in finches %}
<div class="card">
            <a href="{% url 'finches_detail' finch.id %}">
            <div class="card-content">
                <span class="card-title">{{ finch.name }}</span>
                <p>Breed: {{ finch.breed }}</p>
                <p>Descripition: {{ finch.description }}</p>
                {% if finch.age > 0 %}
                    <p>Age: {{ finch.age }}</p>
                {% else %}
                    <p>Age: Kitten</p>
                {% endif %}

            </div>
        </a>
    </div>
{% endfor  %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Home | Finch Collector
{% endblock %}

{% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block title %}

Are You Sure you want to Delete {{ object.name }}? | Finch Collector

{% endblock %}

{% block content %}

<h1>Are you sure you want to delete <span class="blue-text">{{ object.name }}</span>?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'finches_detail' object.id ">No - Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block title %}

Add a new Finch | Finch Collector

{% endblock %}

{% block content %}

{% if object %}
<h1>Edit {{ object.name }}'s Details</h1>
{% else %}
<h1>Add a new Finch</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="{% if object %} Update {% else %} Add New {% endif %}" class="btn green" />
</form>


{% endblock %}